#!/usr/bin/env bash
source /usr/bin/pwnlib

# we need to decrypt something
if is_crypted_mode; then
  while ! is_decrypted; do
    echo "Waiting for decryption..."
    sleep 1
  done
fi

if is_auto_mode; then
  systemctl restart bettercap
  sleep 3
  /opt/.pwn/bin/pwnagotchi
else
  /opt/.pwn/bin/pwnagotchi --manual
fi
